"""empty message

Revision ID: 768875a98c07
Revises: 
Create Date: 2024-09-12 04:31:23.455402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768875a98c07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('thread_id', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
        sa.UniqueConstraint('email', name=op.f('uq_user_email')),
        sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )

    op.create_table('exams',
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('create_date', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_exams_user_id_user')),
        sa.PrimaryKeyConstraint('exam_id', name=op.f('pk_exams'))
    )
    op.create_index(op.f('ix_exams_exam_id'), 'exams', ['exam_id'], unique=False)

    op.create_table('test_questions',
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('correct_choice_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name=op.f('fk_test_questions_exam_id_exams'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('question_id', name=op.f('pk_test_questions'))
    )
    op.create_index(op.f('ix_test_questions_question_id'), 'test_questions', ['question_id'], unique=False)

    op.create_table('choices',
        sa.Column('choice_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_correct', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['test_questions.question_id'], name=op.f('fk_choices_question_id_test_questions'), onupdate='CASCADE'),
        sa.PrimaryKeyConstraint('choice_id', name=op.f('pk_choices')),
        sa.UniqueConstraint('question_id', 'content', name='uq_question_choice_content')
    )
    op.create_index(op.f('ix_choices_choice_id'), 'choices', ['choice_id'], unique=False)
    
    op.create_table('gemini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_gemini_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gemini'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_question_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_table('attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('attempt_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name=op.f('fk_attempts_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_attempts_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_attempts'))
    )
    op.create_index(op.f('ix_attempts_attempt_id'), 'attempts', ['attempt_id'], unique=False)
    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_choice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.attempt_id'], name=op.f('fk_answers_attempt_id_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.question_id'], name=op.f('fk_answers_question_id_test_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['choices.choice_id'], name=op.f('fk_answers_selected_choice_id_choices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('answer_id', name=op.f('pk_answers'))
    )
    op.create_index(op.f('ix_answers_answer_id'), 'answers', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_answer_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_attempts_attempt_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('question')
    op.drop_table('gemini')
    op.drop_index(op.f('ix_exams_exam_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_table('user')
    op.drop_index(op.f('ix_test_questions_question_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_choices_choice_id'), table_name='choices')
    op.drop_table('choices')
    # ### end Alembic commands ###
